import fs from 'fs';
import path from 'path';
import { AuditReport, ScanFinding } from '../models/result';

export function generateMarkdownReport(reportDir: string, report: AuditReport) {
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  const icon = (status: string) => {
    switch (status) {
      case 'pass': return '✅';
      case 'fail': return '❌';
      case 'warn': return '⚠️';
      case 'skipped': return '⏭️';
      default: return '❓';
    }
  };

  const severityIcon = (sev: string) => {
    switch (sev) {
      case 'critical': return '🚨';
      case 'high': return '⛔';
      case 'medium': return '⚠️';
      case 'low': return 'ℹ️';
      default: return '🔍';
    }
  }

  let md = `# Bee-Audit Security & Quality Report\n\n`;
  md += `## System Status: ${icon(report.summary.status)} **${report.summary.status.toUpperCase()}**\n\n`;

  md += `### 📊 Scores\n`;
  md += `- **Quality Score**: ${report.scores.quality}/100\n`;
  md += `- **Security Score**: ${report.scores.security}/100\n`;
  md += `- **Dependencies Score**: ${report.scores.dependencies}/100\n`;
  if (report.security.dast.status !== 'skipped') {
    md += `- **Runtime Score**: ${report.scores.runtime}/100\n`;
  }
  md += `- **Overall Score**: **${report.scores.overall}/100**\n\n`;

  md += `### 🏗️ Workspaces (Static & Hygiene)\n`;
  for (const ws of report.workspaces) {
    md += `**Workspace: \`${ws.workspace}\`**\n`;
    md += `- Linting: ${icon(ws.lint.status)} ${ws.lint.status.toUpperCase()} ${ws.lint.error ? `(${ws.lint.error})` : ''}\n`;
    md += `- Type Check: ${icon(ws.typeCheck.status)} ${ws.typeCheck.status.toUpperCase()} ${ws.typeCheck.error ? `(${ws.typeCheck.error})` : ''}\n`;
    md += `- Tests: ${icon(ws.test.status)} ${ws.test.status.toUpperCase()} ${ws.test.error ? `(${ws.test.error})` : ''}\n\n`;
  }

  const renderFindings = (findings: ScanFinding[]) => {
    if (findings.length === 0) return ' None detected.\n';
    let fmd = '\n';
    findings.forEach(f => {
      fmd += `  - ${severityIcon(f.severity)} **[${f.severity.toUpperCase()}]** ${f.summary}\n`;
      if (f.file) fmd += `    - File: \`${f.file}\` (Line: ${f.line || '?'})\n`;
      if (f.recommendation) fmd += `    - Fix: ${f.recommendation}\n`;
    });
    return fmd;
  };

  md += `### 🛡️ Code Security (SAST & Secrets)\n`;
  md += `- **Gitleaks (Secrets)**: ${icon(report.security.secrets.status)} ${report.security.secrets.error || (report.security.secrets.findings.length > 0 ? report.security.secrets.findings.length + ' findings' : 'Clean')}\n`;
  
  if (report.security.semgrep) {
    if (report.security.semgrep.status === 'skipped') {
      md += `- **Semgrep CE (SAST)**: ${icon('skipped')} SKIPPED (${report.security.semgrep.error})\n`;
    } else {
      md += `- **Semgrep CE (SAST)**: ${icon(report.security.semgrep.status)} ${report.security.semgrep.error || ''}`;
      md += renderFindings(report.security.semgrep.findings);
    }
  }

  md += `- **Internal Baseline SAST**: ${icon(report.security.sast.status)} ${report.security.sast.error || ''}`;
  md += renderFindings(report.security.sast.findings);

  md += `\n### 📦 Dependency Audit\n`;
  md += `- **Dependencies**: ${icon(report.security.dependencies.status)} ${report.security.dependencies.error || (report.security.dependencies.findings.length > 0 ? report.security.dependencies.findings.length + ' issues' : 'Clean')}\n`;

  md += `\n### 🌐 Runtime Security (DAST & E2E Logic)\n`;
  md += `- **DAST (ZAP)**: ${icon(report.security.dast.status)} ${report.security.dast.error || ''}\n`;
  md += `- **Business Logic (Playwright)**: ${icon(report.security.logic.status)} ${report.security.logic.error || ''}\n`;

  md += `\n---\n> _Generated by Bee-Audit CLI (${report.metadata.timestamp})_\n`;
  if (report.metadata.runtimeTarget) md += `> _Runtime Target: ${report.metadata.runtimeTarget}_\n`;

  const dest = path.join(reportDir, 'summary.md');
  fs.writeFileSync(dest, md, 'utf-8');
}
