import fs from 'fs';
import path from 'path';
import { AuditReport } from '../models/result';

export function generateMarkdownReport(reportDir: string, report: AuditReport) {
  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  const icon = (status: string) => {
    switch (status) {
      case 'pass': return '✅';
      case 'fail': return '❌';
      case 'warn': return '⚠️';
      case 'skipped': return '⏭️';
      default: return '❓';
    }
  };

  let md = `# Bee-Audit Security & Quality Report\n\n`;
  md += `## System Status: ${icon(report.summary.status)} **${report.summary.status.toUpperCase()}**\n\n`;

  md += `### Workspaces Overview\n`;
  for (const ws of report.workspaces) {
    md += `**Workspace: \`${ws.workspace}\`**\n`;
    md += `- Linting: ${icon(ws.lint.status)} ${ws.lint.status.toUpperCase()} ${ws.lint.error ? `(${ws.lint.error})` : ''}\n`;
    md += `- Type Check: ${icon(ws.typeCheck.status)} ${ws.typeCheck.status.toUpperCase()} ${ws.typeCheck.error ? `(${ws.typeCheck.error})` : ''}\n`;
    md += `- Tests: ${icon(ws.test.status)} ${ws.test.status.toUpperCase()} ${ws.test.error ? `(${ws.test.error})` : ''}\n\n`;
  }

  md += `### Security & Secrets\n`;
  md += `- **Gitleaks**: ${icon(report.security.secrets.status)} ${report.security.secrets.error || 'Clean'}\n`;
  md += `- **Dependencies**: ${icon(report.security.dependencies.status)} ${report.security.dependencies.error || 'Clean'}\n\n`;

  md += `> _Generated by Bee-Audit CLI_\n`;

  const dest = path.join(reportDir, 'summary.md');
  fs.writeFileSync(dest, md, 'utf-8');
}
